import React from 'react';
import {
    AlertCircle,
    ArrowDown,
    Award,
    BarChart3,
    Bell,
    BookOpen,
    Briefcase,
    Calculator,
    Calendar,
    CalendarCheck,
    CalendarDays,
    CalendarX,
    Camera,
    Car,
    Check,
    CheckCheck,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Circle,
    CircleDot,
    CircleHelp,
    CircleUser,
    ClipboardCheck,
    Clock3,
    CloudUpload,
    Code2,
    Coffee,
    Compass,
    Copy,
    Crown,
    DoorOpen,
    Download,
    EllipsisVertical,
    Eraser,
    Eye,
    Fan,
    FileInput,
    FileSpreadsheet,
    Filter,
    FilterX,
    Folder,
    Footprints,
    GanttChart,
    Gauge,
    Gift,
    GraduationCap,
    Headset,
    Heart,
    History,
    Hourglass,
    IdCard,
    Images,
    Inbox,
    Info,
    Key,
    Laptop,
    Layers3,
    Lightbulb,
    List,
    ListChecks,
    ListOrdered,
    ListTodo,
    LoaderCircle,
    LocateFixed,
    Lock,
    LockOpen,
    LogOut,
    Medal,
    Menu,
    MessageSquare,
    MessageSquareText,
    Minus,
    Pen,
    Percent,
    Phone,
    PhoneCall,
    Play,
    PlayCircle,
    Plus,
    QrCode,
    RefreshCw,
    RotateCw,
    Search,
    Save,
    Send,
    Settings,
    Shield,
    Shuffle,
    SlidersHorizontal,
    Sparkles,
    Sprout,
    Square,
    Star,
    Table,
    Target,
    ThumbsUp,
    ToggleLeft,
    ToggleRight,
    Trash2,
    TrendingUp,
    TriangleAlert,
    Trophy,
    Upload,
    User,
    UserCheck,
    UserCog,
    UserPen,
    UserPlus,
    Users,
    UserX,
    VideoOff,
    Workflow,
    Wrench,
    X,
    XCircle
} from 'lucide-react';

const TOKEN_TO_ICON = {
    'fa-angle-left': 'ChevronLeft',
    'fa-angle-right': 'ChevronRight',
    'fa-arrow-down': 'ArrowDown',
    'fa-arrows-rotate': 'RefreshCw',
    'fa-award': 'Award',
    'fa-birthday-cake': 'Gift',
    'fa-cake-candles': 'Gift',
    'fa-ban': 'XCircle',
    'fa-bars': 'Menu',
    'fa-bell': 'Bell',
    'fa-book': 'BookOpen',
    'fa-briefcase': 'Briefcase',
    'fa-bullseye': 'Target',
    'fa-calculator': 'Calculator',
    'fa-calendar': 'Calendar',
    'fa-calendar-alt': 'CalendarDays',
    'fa-calendar-check': 'CalendarCheck',
    'fa-calendar-day': 'Calendar',
    'fa-calendar-days': 'CalendarDays',
    'fa-calendar-times': 'CalendarX',
    'fa-calendar-user': 'Calendar',
    'fa-calendar-xmark': 'CalendarX',
    'fa-camera': 'Camera',
    'fa-chalkboard-teacher': 'GraduationCap',
    'fa-chart-bar': 'BarChart3',
    'fa-chart-gantt': 'GanttChart',
    'fa-chart-line': 'TrendingUp',
    'fa-check': 'Check',
    'fa-check-circle': 'CheckCircle2',
    'fa-check-double': 'CheckCheck',
    'fa-chevron': 'ChevronDown',
    'fa-chevron-down': 'ChevronDown',
    'fa-chevron-left': 'ChevronLeft',
    'fa-chevron-right': 'ChevronRight',
    'fa-chevron-up': 'ChevronUp',
    'fa-circle-check': 'CheckCircle2',
    'fa-circle-dot': 'CircleDot',
    'fa-circle-exclamation': 'AlertCircle',
    'fa-circle-info': 'Info',
    'fa-circle-notch': 'LoaderCircle',
    'fa-circle-question': 'CircleHelp',
    'fa-circle-xmark': 'XCircle',
    'fa-clipboard-check': 'ClipboardCheck',
    'fa-clipboard-list': 'ListChecks',
    'fa-clock': 'Clock3',
    'fa-clock-rotate-left': 'History',
    'fa-cloud-upload-alt': 'CloudUpload',
    'fa-code': 'Code2',
    'fa-coffee': 'Coffee',
    'fa-cog': 'Settings',
    'fa-comment-dots': 'MessageSquare',
    'fa-comments': 'MessageSquareText',
    'fa-compass': 'Compass',
    'fa-copy': 'Copy',
    'fa-crown': 'Crown',
    'fa-diagram-project': 'Workflow',
    'fa-door-open': 'DoorOpen',
    'fa-download': 'Download',
    'fa-edit': 'Pen',
    'fa-ellipsis-v': 'EllipsisVertical',
    'fa-eraser': 'Eraser',
    'fa-exclamation-circle': 'AlertCircle',
    'fa-exclamation-triangle': 'TriangleAlert',
    'fa-eye': 'Eye',
    'fa-fan': 'Fan',
    'fa-file-csv': 'FileSpreadsheet',
    'fa-file-export': 'FileInput',
    'fa-file-excel': 'FileSpreadsheet',
    'fa-file-import': 'FileInput',
    'fa-filter': 'Filter',
    'fa-filter-circle-xmark': 'FilterX',
    'fa-folder': 'Folder',
    'fa-gear': 'Settings',
    'fa-gift': 'Gift',
    'fa-graduation-cap': 'GraduationCap',
    'fa-hand-point-left': 'ChevronLeft',
    'fa-headset': 'Headset',
    'fa-heart': 'Heart',
    'fa-history': 'History',
    'fa-hourglass-half': 'Hourglass',
    'fa-id-card': 'IdCard',
    'fa-images': 'Images',
    'fa-inbox': 'Inbox',
    'fa-info-circle': 'Info',
    'fa-key': 'Key',
    'fa-laptop-house': 'Laptop',
    'fa-layer-group': 'Layers3',
    'fa-magnifying-glass': 'Search',
    'fa-lightbulb': 'Lightbulb',
    'fa-list': 'List',
    'fa-location-crosshairs': 'LocateFixed',
    'fa-list-alt': 'List',
    'fa-list-check': 'ListChecks',
    'fa-list-ol': 'ListOrdered',
    'fa-list-ul': 'List',
    'fa-lock': 'Lock',
    'fa-medal': 'Medal',
    'fa-minus': 'Minus',
    'fa-mug-hot': 'Coffee',
    'fa-paper-plane': 'Send',
    'fa-pen': 'Pen',
    'fa-pencil-alt': 'Pen',
    'fa-percent': 'Percent',
    'fa-phone': 'Phone',
    'fa-phone-alt': 'PhoneCall',
    'fa-play': 'Play',
    'fa-play-circle': 'PlayCircle',
    'fa-plus': 'Plus',
    'fa-qrcode': 'QrCode',
    'fa-right-left': 'Shuffle',
    'fa-shuffle': 'Shuffle',
    'fa-exchange-alt': 'Shuffle',
    'fa-arrows-left-right': 'Shuffle',
    'fa-question-circle': 'CircleHelp',
    'fa-random': 'Shuffle',
    'fa-redo': 'RotateCw',
    'fa-rotate': 'RotateCw',
    'fa-running': 'Footprints',
    'fa-save': 'Save',
    'fa-search': 'Search',
    'fa-seedling': 'Sprout',
    'fa-shield-alt': 'Shield',
    'fa-sign-out-alt': 'LogOut',
    'fa-sliders': 'SlidersHorizontal',
    'fa-sliders-h': 'SlidersHorizontal',
    'fa-sparkles': 'Sparkles',
    'fa-spinner': 'LoaderCircle',
    'fa-sort': 'ListOrdered',
    'fa-sort-amount-down': 'ListOrdered',
    'fa-arrow-down-wide-short': 'ListOrdered',
    'fa-star': 'Star',
    'fa-stop': 'Square',
    'fa-sync-alt': 'RefreshCw',
    'fa-table': 'Table',
    'fa-tachometer-alt': 'Gauge',
    'fa-tasks': 'ListTodo',
    'fa-taxi': 'Car',
    'fa-telegram-plane': 'Send',
    'fa-thumbs-up': 'ThumbsUp',
    'fa-times': 'X',
    'fa-times-circle': 'XCircle',
    'fa-toggle-off': 'ToggleLeft',
    'fa-toggle-on': 'ToggleRight',
    'fa-tools': 'Wrench',
    'fa-trash': 'Trash2',
    'fa-trash-alt': 'Trash2',
    'fa-triangle-exclamation': 'TriangleAlert',
    'fa-trophy': 'Trophy',
    'fa-unlock-keyhole': 'LockOpen',
    'fa-upload': 'Upload',
    'fa-user': 'User',
    'fa-user-check': 'UserCheck',
    'fa-user-circle': 'CircleUser',
    'fa-user-clock': 'User',
    'fa-user-cog': 'UserCog',
    'fa-user-edit': 'UserPen',
    'fa-user-graduate': 'GraduationCap',
    'fa-user-plus': 'UserPlus',
    'fa-user-tag': 'User',
    'fa-user-tie': 'User',
    'fa-user-shield': 'Shield',
    'fa-user-slash': 'UserX',
    'fa-user-times': 'UserX',
    'fa-users': 'Users',
    'fa-users-cog': 'Users',
    'fa-video-slash': 'VideoOff',
    'fa-xmark': 'X'
};

const ICON_COMPONENTS = {
    AlertCircle,
    ArrowDown,
    Award,
    BarChart3,
    Bell,
    BookOpen,
    Briefcase,
    Calculator,
    Calendar,
    CalendarCheck,
    CalendarDays,
    CalendarX,
    Camera,
    Car,
    Check,
    CheckCheck,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Circle,
    CircleDot,
    CircleHelp,
    CircleUser,
    ClipboardCheck,
    Clock3,
    CloudUpload,
    Code2,
    Coffee,
    Compass,
    Copy,
    Crown,
    DoorOpen,
    Download,
    EllipsisVertical,
    Eraser,
    Eye,
    Fan,
    FileInput,
    FileSpreadsheet,
    Filter,
    FilterX,
    Folder,
    Footprints,
    GanttChart,
    Gauge,
    Gift,
    GraduationCap,
    Headset,
    Heart,
    History,
    Hourglass,
    IdCard,
    Images,
    Inbox,
    Info,
    Key,
    Laptop,
    Layers3,
    Lightbulb,
    List,
    ListChecks,
    ListOrdered,
    ListTodo,
    LoaderCircle,
    LocateFixed,
    Lock,
    LockOpen,
    LogOut,
    Medal,
    Menu,
    MessageSquare,
    MessageSquareText,
    Minus,
    Pen,
    Percent,
    Phone,
    PhoneCall,
    Play,
    PlayCircle,
    Plus,
    QrCode,
    RefreshCw,
    RotateCw,
    Search,
    Save,
    Send,
    Settings,
    Shield,
    Shuffle,
    SlidersHorizontal,
    Sparkles,
    Sprout,
    Square,
    Star,
    Table,
    Target,
    ThumbsUp,
    ToggleLeft,
    ToggleRight,
    Trash2,
    TrendingUp,
    TriangleAlert,
    Trophy,
    Upload,
    User,
    UserCheck,
    UserCog,
    UserPen,
    UserPlus,
    Users,
    UserX,
    VideoOff,
    Workflow,
    Wrench,
    X,
    XCircle
};

const FA_META_TOKENS = new Set([
    'fa-solid',
    'fa-regular',
    'fa-brands',
    'fas',
    'far',
    'fab',
    'fa-lg',
    'fa-spin'
]);

const extractTokens = (className) => (typeof className === 'string' ? className.split(/\s+/).filter(Boolean) : []);

const pickIconToken = (tokens) => tokens.find((token) => TOKEN_TO_ICON[token]);

const normalizeClassName = (tokens) =>
    tokens
        .filter((token) => !FA_META_TOKENS.has(token) && !TOKEN_TO_ICON[token])
        .join(' ')
        .trim();

const FaIcon = ({ className = '', style, ...rest }) => {
    const tokens = extractTokens(className);
    const iconToken = pickIconToken(tokens);
    const iconName = iconToken ? TOKEN_TO_ICON[iconToken] : null;
    const IconComponent = (iconName && ICON_COMPONENTS[iconName]) || Circle;
    const shouldSpin = tokens.includes('fa-spin');
    const cleanClassName = normalizeClassName(tokens);
    const mergedClassName = [cleanClassName, shouldSpin ? 'animate-spin' : '']
        .filter(Boolean)
        .join(' ')
        .trim();
    const finalClassName = ['inline-block align-middle', mergedClassName].filter(Boolean).join(' ');
    const sizeStyle = { width: '1em', height: '1em', ...style };

    return <IconComponent className={finalClassName} style={sizeStyle} {...rest} />;
};

export default FaIcon;
